### ISSUE TITLE
generate docs

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/AdKGromacsTutorial#2]
We can use travis to generate the docs and push to the gh-pages branch (or use master directly) or use Read The Docs.

In any case, the docs should be live somewhere.

**Comment by sseyler** [comment]
The docs for the *most basic* version of the tutorial are now live on RTD. It follows the version made for BioXFEL in summer 2016, which was in turn adapted from the  [AdKTutorial from  PHY 598 – Simulation approaches to Bio- and Nanophysics](https://becksteinlab.physics.asu.edu/pages/courses/2013/SimBioNano/13/AdKTutorial/).

There are now two things left to do:
1. update the files and directories to ensure consistency with the actual documentation
2. create an "advanced" version of the tutorial that has bash scripts, multi-step equilibration, and documentation specific to members of the lab (e.g., `module load gromacs/5.1.3/...`, etc.)

I'll create separate issues to deal with these tasks.
